spring:
  application:
    name: beacon-cache
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        grpc-enabled: false
      discovery:
        server-addr: localhost:8848
        grpc-enabled: false
  config:
    import:
      - nacos:beacon-cache-dev.yml?refreshEnabled=true

