package com.peng.sms.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class StandardReport implements Serializable {

    /**
     * Used to conveniently query the status report push information of the client
     * during secondary callbacks from the gateway operator
     */

    private String apikey;

    /**
     * Unique identifier for the current SMS, generated by the Snowflake algorithm (reserved)
     */
    private Long sequenceId;

    /**
     * Client ID, obtained from the cache module based on apikey
     */
    private Long clientId;


    /**
     * Client-specific UID, passed in the request
     */
    private String uid;

    /**
     * Target mobile number, passed in the client request
     */
    private String mobile;

    /**
     * SMS sending time, the current system time
     */
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    private LocalDateTime sendTime;

    /**
     * SMS sending status:
     * 0 - waiting/sending, 1 - success, 2 - failure. Default is 0
     */
    private int reportState;

    /**
     * Reason for SMS sending failure, recorded in this field
     */
    private String errorMsg;

    /**
     * Callback information
     */
    private Integer isCallback;
    private String callbackUrl;

    /**
     * Number of times the report push has been retried
     */
    private Integer resendCount = 0;

    /**
     * If this is the first modification operation, false;
     * if it is the second delivery, logs should be recorded directly
     */
    private Boolean reUpdate = false;
}
