
spring:
  application:
    name: beacon-api
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        grpc-enabled: false
      discovery:
        server-addr: localhost:8848
        grpc-enabled: false
  config:
    import:
      - nacos:beacon-api-dev.yml?refreshEnabled=true
server:
  port: 18001
  address: 0.0.0.0

# the requeset head
headers:
  x-forwarded-for,x-real-ip,proxy-client-ip,wl-proxy-client-ip,http_client_ip